export const dynamic = 'force-dynamic';
import { NextRequest } from "next/server";

/**
 * Generates a professional clinical findings summary from prediction metrics.
 * Uses template-based generation with clinical language — no external API needed.
 */
export async function POST(req: NextRequest) {
  const body = await req.json();
  const { tumorType, confidence, volumeCm3, regionVolumes, classProbs, diceScores } = body;

  const confPct = ((confidence || 0) * 100).toFixed(1);
  const totalVol = (volumeCm3 || 0).toFixed(2);
  const etVol = regionVolumes?.enhancing_tumor ?? "N/A";
  const ncVol = regionVolumes?.necrotic_core ?? "N/A";
  const edVol = regionVolumes?.peritumoral_edema ?? "N/A";
  const wtVol = regionVolumes?.whole_tumor ?? "N/A";
  const tcVol = regionVolumes?.tumor_core ?? "N/A";

  // Determine clinical severity and language
  const isHGG = tumorType?.toLowerCase().includes("hgg") || tumorType?.toLowerCase().includes("high");
  const isLGG = tumorType?.toLowerCase().includes("lgg") || tumorType?.toLowerCase().includes("low");
  const isNoTumor = tumorType?.toLowerCase().includes("no tumor");
  const highConf = confidence > 0.8;

  let paragraph1: string;
  let paragraph2: string;
  let paragraph3: string;

  if (isNoTumor) {
    paragraph1 = `FINDINGS: AI-assisted analysis of multi-modal MRI sequences (T1, T1-weighted contrast-enhanced, T2, FLAIR) was performed using a 3D Attention U-Net segmentation model (BraTSNet). The automated analysis did not identify any significant intra-axial or extra-axial mass lesion. No areas of abnormal enhancement, restricted diffusion, or significant mass effect were observed. The model confidence for the absence of tumor was ${confPct}%.`;

    paragraph2 = `VOLUMETRIC ANALYSIS: Total segmented volume was ${totalVol} cm³, which is within normal limits. No enhancing tissue, necrotic components, or significant peritumoral signal abnormality were detected.`;

    paragraph3 = `IMPRESSION: No evidence of intracranial neoplasm identified on AI-assisted analysis. Clinical correlation is recommended. This automated analysis should be verified by a board-certified neuroradiologist. If clinical suspicion remains high, follow-up imaging or advanced techniques (MR spectroscopy, perfusion imaging) may be considered.`;

  } else if (isHGG) {
    const severity = parseFloat(totalVol) > 50 ? "large" : parseFloat(totalVol) > 20 ? "moderate-sized" : "small";
    const edemaNote = parseFloat(String(edVol)) > 30
      ? "Extensive peritumoral edema is present, suggesting significant mass effect and possible elevated intracranial pressure."
      : parseFloat(String(edVol)) > 10
        ? "Moderate peritumoral edema is noted, consistent with expected perilesional vasogenic changes."
        : "Mild peritumoral edema is present.";

    const necroticNote = parseFloat(String(ncVol)) > 5
      ? `A significant necrotic core measuring ${ncVol} cm³ is identified, which is characteristic of WHO Grade IV glioblastoma and indicative of aggressive tumor biology with central hypoxia.`
      : `A necrotic core of ${ncVol} cm³ is present, consistent with areas of central tumor necrosis.`;

    paragraph1 = `FINDINGS: AI-assisted analysis of multi-modal MRI sequences (T1, T1ce, T2, FLAIR) was performed using a 3D Attention U-Net segmentation model (BraTSNet). The analysis reveals a ${severity} intra-axial mass lesion consistent with High-Grade Glioma (HGG), identified with a model confidence of ${confPct}%. The total tumor volume measures ${totalVol} cm³ encompassing the whole tumor region. Enhancing tumor component measures ${etVol} cm³, suggesting active tumor with disrupted blood-brain barrier. ${necroticNote}`;

    paragraph2 = `VOLUMETRIC ANALYSIS: Whole Tumor (WT): ${wtVol} cm³ | Tumor Core (TC): ${tcVol} cm³ | Enhancing Tumor (ET): ${etVol} cm³ | Necrotic Core: ${ncVol} cm³ | Peritumoral Edema: ${edVol} cm³. ${edemaNote}${classProbs ? ` Classification probabilities — No Tumor: ${(classProbs.no_tumor * 100).toFixed(1)}%, LGG: ${(classProbs.lgg * 100).toFixed(1)}%, HGG: ${(classProbs.hgg * 100).toFixed(1)}%.` : ""}${diceScores ? ` Segmentation confidence metrics — Whole Tumor Dice: ${diceScores.wt_dice}, Tumor Core Dice: ${diceScores.tc_dice}, Enhancing Tumor Dice: ${diceScores.et_dice}.` : ""}`;

    paragraph3 = `IMPRESSION: Findings are ${highConf ? "highly" : "moderately"} suggestive of a high-grade glioma (WHO Grade III-IV), potentially glioblastoma multiforme (GBM). The presence of ${parseFloat(String(etVol)) > 5 ? "prominent" : "some"} enhancement with central necrosis and peritumoral edema is characteristic of aggressive glial neoplasm. Neurosurgical consultation for tissue diagnosis and molecular profiling (IDH mutation, MGMT promoter methylation, 1p/19q codeletion) is recommended. DISCLAIMER: This is an AI-assisted preliminary analysis generated by the NeuroScan AI system. All findings must be independently verified by a qualified neuroradiologist before any clinical decisions are made.`;

  } else if (isLGG) {
    paragraph1 = `FINDINGS: AI-assisted analysis of multi-modal MRI sequences (T1, T1ce, T2, FLAIR) was performed using a 3D Attention U-Net segmentation model (BraTSNet). The analysis identifies an intra-axial lesion consistent with Low-Grade Glioma (LGG), detected with a model confidence of ${confPct}%. The total lesion volume measures ${totalVol} cm³. Minimal or absent contrast enhancement (${etVol} cm³) is noted, which is characteristic of lower-grade diffuse gliomas.`;

    paragraph2 = `VOLUMETRIC ANALYSIS: Whole Tumor (WT): ${wtVol} cm³ | Tumor Core (TC): ${tcVol} cm³ | Enhancing Tumor (ET): ${etVol} cm³ | Necrotic Core: ${ncVol} cm³ | Peritumoral Edema: ${edVol} cm³. The relatively ${parseFloat(String(etVol)) < 2 ? "minimal enhancement pattern" : "limited enhancement"} and ${parseFloat(String(ncVol)) < 2 ? "absence of significant necrosis" : "limited necrotic component"} are consistent with a lower-grade neoplasm.${classProbs ? ` Classification probabilities — No Tumor: ${(classProbs.no_tumor * 100).toFixed(1)}%, LGG: ${(classProbs.lgg * 100).toFixed(1)}%, HGG: ${(classProbs.hgg * 100).toFixed(1)}%.` : ""}${diceScores ? ` Segmentation confidence — WT Dice: ${diceScores.wt_dice}, TC Dice: ${diceScores.tc_dice}, ET Dice: ${diceScores.et_dice}.` : ""}`;

    paragraph3 = `IMPRESSION: Findings are suggestive of a low-grade glioma (WHO Grade II), likely a diffuse astrocytoma or oligodendroglioma. Molecular profiling (IDH1/2 mutation status, 1p/19q codeletion, ATRX expression) is essential for accurate subclassification per the 2021 WHO CNS tumor classification. Serial imaging surveillance is recommended to monitor for potential malignant transformation. DISCLAIMER: This is an AI-assisted preliminary analysis generated by the NeuroScan AI system. All findings must be independently verified by a qualified neuroradiologist before any clinical decisions are made.`;

  } else {
    // Generic / Unknown type
    paragraph1 = `FINDINGS: AI-assisted analysis of multi-modal MRI sequences (T1, T1ce, T2, FLAIR) was performed using a 3D Attention U-Net segmentation model (BraTSNet). The analysis detects an intra-axial lesion classified as "${tumorType}" with a model confidence of ${confPct}%. Total lesion volume measures ${totalVol} cm³.`;

    paragraph2 = `VOLUMETRIC ANALYSIS: Whole Tumor (WT): ${wtVol} cm³ | Tumor Core (TC): ${tcVol} cm³ | Enhancing Tumor (ET): ${etVol} cm³ | Necrotic Core: ${ncVol} cm³ | Peritumoral Edema: ${edVol} cm³.${classProbs ? ` Classification probabilities — No Tumor: ${(classProbs.no_tumor * 100).toFixed(1)}%, LGG: ${(classProbs.lgg * 100).toFixed(1)}%, HGG: ${(classProbs.hgg * 100).toFixed(1)}%.` : ""}`;

    paragraph3 = `IMPRESSION: An intracranial lesion has been identified. Further characterization with advanced imaging techniques and tissue sampling is recommended. DISCLAIMER: This is an AI-assisted preliminary analysis. All findings must be verified by a qualified neuroradiologist.`;
  }

  const fullSummary = `${paragraph1}\n\n${paragraph2}\n\n${paragraph3}`;

  // Stream the text character-by-character for the typewriter effect
  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      // Stream in chunks of ~8 characters for smooth typewriter effect
      const chunkSize = 8;
      for (let i = 0; i < fullSummary.length; i += chunkSize) {
        const chunk = fullSummary.slice(i, i + chunkSize);
        controller.enqueue(encoder.encode(chunk));
        // Small delay for typewriter effect (~30ms per chunk)
        await new Promise((r) => setTimeout(r, 15));
      }
      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Transfer-Encoding": "chunked",
    },
  });
}
